import { Dimensions, StyleSheet } from "react-native";
const { width: screenWidth } = Dimensions.get("window");
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAFAFA",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F9FAFB",
    justifyContent: "center",
    alignItems: "center",
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
  },
  headerSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 2,
  },
  headerRight: {
    width: 40,
  },
  toggleContainer: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#FFFFFF",
  },
  toggleWrapper: {
    flexDirection: "row",
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    padding: 4,
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 8,
  },
  toggleButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: "transparent",
  },
  toggleButtonActiveExpense: {
    backgroundColor: "#EF4444",
  },
  toggleButtonActiveIncome: {
    backgroundColor: "#10B981",
  },
  toggleText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#6B7280",
    marginLeft: 8,
  },
  toggleTextActiveExpense: {
    color: "white",
  },
  toggleTextActiveIncome: {
    color: "white",
  },
  content: {
    flex: 1,
  },
  amountCard: {
    margin: 20,
    borderRadius: 20,
    overflow: "hidden",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  amountGradient: {
    padding: 32,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
  },
  amountLabel: {
    fontSize: 16,
    color: "#6B7280",
    marginBottom: 16,
  },
  amountInputContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  currencySymbol: {
    fontSize: 48,
    fontWeight: "300",
    marginRight: 8,
  },
  amountInput: {
    fontSize: 48,
    fontWeight: "300",
    minWidth: 120,
    textAlign: "left",
  },
  formCard: {
    margin: 20,
    marginTop: 0,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  inputContainer: {
    marginBottom: 24,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 8,
  },
  textInput: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: "#111827",
    backgroundColor: "#F9FAFB",
  },
  selectButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#F9FAFB",
  },
  selectContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  selectText: {
    fontSize: 16,
    color: "#111827",
    marginLeft: 12,
  },
  categoryIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  splitInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F9FAFB",
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  splitText: {
    fontSize: 14,
    color: "#6B7280",
  },
  splitButton: {
    backgroundColor: "#8B5CF6",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  splitButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: "white",
  },
  submitContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  submitButton: {
    borderRadius: 16,
    overflow: "hidden",
  },
  submitGradient: {
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  submitText: {
    fontSize: 18,
    fontWeight: "600",
    color: "white",
    marginLeft: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 20,
    width: "100%",
    maxWidth: 400,
    maxHeight: "80%",
    elevation: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F9FAFB",
    justifyContent: "center",
    alignItems: "center",
  },
  categoryItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  categoryItemSelected: {
    backgroundColor: "#F0FDF4",
  },
  categoryName: {
    fontSize: 16,
    color: "#111827",
    marginLeft: 12,
    flex: 1,
  },
  memberItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  memberItemSelected: {
    backgroundColor: "#F0FDF4",
  },
  memberAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#8B5CF6",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  memberInitial: {
    fontSize: 14,
    fontWeight: "700",
    color: "white",
  },
  memberName: {
    fontSize: 16,
    color: "#111827",
    flex: 1,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E0E7FF",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 8,
    marginBottom: 8,
  },
  chipSelected: {
    backgroundColor: "#D1FAE5",
  },
  chipText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#10B981",
    marginLeft: 8,
  },
  improvedModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(30, 41, 59, 0.45)",
    justifyContent: "center",
    alignItems: "center",
  },
  improvedModalContent: {
    backgroundColor: "#fff",
    borderRadius: 20,
    marginHorizontal: 16,
    width: "90%",
    maxWidth: 400,
    maxHeight: "85%",
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  modalScrollView: {
    flex: 1,
  },
  modalScrollContent: {
    paddingBottom: 20,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#374151",
    marginTop: 12,
    marginBottom: 4,
    marginLeft: 20,
  },
  categoryCardsContainer: {
    paddingHorizontal: 16,
  },
  categoryCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginHorizontal: 4,
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  categoryCardSelected: {
    backgroundColor: "#F0FDF4",
    borderWidth: 1,
    borderColor: "#10B981",
  },
  categoryCardContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  categoryCardIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  categoryCardLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: "#374151",
    flex: 1,
  },
  categoryCardLabelSelected: {
    color: "#10B981",
    fontWeight: "600",
  },
  categorySeparator: {
    height: 1,
    backgroundColor: "#F3F4F6",
    marginHorizontal: 20,
    marginVertical: 4,
  },
  addCategoryCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderStyle: "dashed",
  },
  addCategoryCardIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#10B98120",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  addCategoryCardLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: "#10B981",
    flex: 1,
  },
  categoryGridContainer: {
    paddingHorizontal: 8,
  },
  categoryRow: {
    justifyContent: "space-between",
    paddingHorizontal: 4,
  },
  categoryGridCell: {
    width: (screenWidth * 0.9 - 64) / 3,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    backgroundColor: "transparent",
    borderRadius: 8,
    paddingHorizontal: 4,
  },
  categoryGridCellSelected: {
    backgroundColor: "#F0FDF4",
  },
  categoryGridLabel: {
    fontSize: 13,
    color: "#374151",
    textAlign: "center",
    fontWeight: "500",
  },
  categoryGridLabelSelected: {
    color: "#10B981",
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  addCategoryGridCell: {
    width: (screenWidth * 0.9 - 64) / 3,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: "#A7F3D0",
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
    borderStyle: "dashed",
  },
  addCategoryGridLabel: {
    fontSize: 12,
    color: "#10B981",
    fontWeight: "600",
    textAlign: "center",
  },
  classyModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "flex-end",
  },
  classyModalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "85%",
    minHeight: "60%",
    elevation: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
  },
  classyModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  modalHeaderContent: {
    flex: 1,
  },
  classyModalTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 4,
  },
  classyModalSubtitle: {
    fontSize: 14,
    color: "#64748B",
    fontWeight: "400",
  },
  classyCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F8FAFC",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 16,
  },
  classyModalScrollView: {
    flex: 1,
  },
  classyScrollContent: {
    paddingBottom: 24,
  },
  sectionHeaderContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 12,
  },
  classySectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#374151",
    marginLeft: 8,
  },
  recentCategoriesContainer: {
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  recentCategoryChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  recentCategoryChipSelected: {
    backgroundColor: "#F0FDF4",
    borderColor: "#10B981",
  },
  recentChipIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 6,
  },
  recentChipText: {
    fontSize: 13,
    fontWeight: "500",
    color: "#475569",
  },
  recentChipTextSelected: {
    color: "#10B981",
    fontWeight: "600",
  },
  classyCategoriesContainer: {
    paddingHorizontal: 16,
  },
  classyCategoryCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginHorizontal: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  classyCategoryCardSelected: {
    backgroundColor: "#FEFFFE",
    borderColor: "#10B981",
    borderWidth: 1.5,
    elevation: 4,
    shadowOpacity: 0.1,
  },
  classyCategoryContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  classyCategoryIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  classyCategoryTextContainer: {
    flex: 1,
  },
  classyCategoryName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 2,
  },
  classyCategoryNameSelected: {
    color: "#10B981",
  },
  classyCategoryType: {
    fontSize: 12,
    color: "#64748B",
    fontWeight: "400",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  selectedIndicator: {
    marginLeft: 12,
  },
  addCategoryCardClassy: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FAFAFA",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginHorizontal: 8,
    marginBottom: 8,
    borderWidth: 1.5,
    borderColor: "#10B981",
    borderStyle: "dashed",
  },
  addCategoryIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#10B98115",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  addCategoryText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#10B981",
    marginBottom: 2,
  },
  addCategorySubtext: {
    fontSize: 12,
    color: "#059669",
    fontWeight: "400",
  },
  addCategoryArrow: {
    marginLeft: 12,
  },
  categoriesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  classyCategoryCardGrid: {
    width: "48%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  categoryCardLeft: {
    marginRight: 4,
  },
  categoryCardRight: {
    marginLeft: 4,
  },
  classyCategoryContentGrid: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  classyCategoryIconContainerGrid: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  classyCategoryTextContainerGrid: {
    flex: 1,
  },
  classyCategoryNameGrid: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 1,
  },
  classyCategoryTypeGrid: {
    fontSize: 10,
    color: "#64748B",
    fontWeight: "400",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  selectedIndicatorGrid: {
    marginLeft: 4,
  },
  addCategoryCardClassyGrid: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FAFAFA",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginTop: 8,
    borderWidth: 1.5,
    borderColor: "#10B981",
    borderStyle: "dashed",
  },
  addCategoryIconContainerGrid: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#10B98115",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  addCategoryTextGrid: {
    fontSize: 14,
    fontWeight: "600",
    color: "#10B981",
    marginBottom: 1,
  },
  addCategorySubtextGrid: {
    fontSize: 10,
    color: "#059669",
    fontWeight: "400",
  },
  addCategoryArrowGrid: {
    marginLeft: 4,
  },
});
